// CommonJS, every file is module (by default)
// Modules - Encapsulated Code (only share minimum)

const names = require('./04_names')
const sayHi = require('./05_utils')
const data = require('./06_alternative_flavor')
require('./07_mind_grenade')
// sayHi('susan')
// sayHi(names.peter)
// sayHi(names.john)
